name: ROS

on:
  pull_request:
  push:
    branches:
      - humble*
      - iron*
      - jazzy*
      - rolling*
      - main
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Cache colcon build
        uses: actions/cache@v5
        with:
          path: |
            build
            install
            log
          key: ${{ runner.os }}-colcon-${{ hashFiles('**/package.xml', 'src/ros2.repos') }}
          restore-keys: |
            ${{ runner.os }}-colcon-
      - name: Test
        uses: ./.github/actions/test/

  lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linter:
          [cppcheck, cpplint, uncrustify, lint_cmake, xmllint, flake8, pep257]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Cache colcon build
        uses: actions/cache@v5
        with:
          path: |
            build
            install
            log
          key: ${{ runner.os }}-colcon-${{ hashFiles('**/package.xml', 'src/ros2.repos') }}
          restore-keys: |
            ${{ runner.os }}-colcon-
      - name: Run linter
        uses: ./.github/actions/lint/
        env:
          LINTER: ${{ matrix.linter }}

  complete:
    name: Tests passed
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: echo "Completed successfully!"
